### ISSUE TITLE
nvm use not working (solved but can someone go through this)

### ISSUE THREAD

**Issue by joaoromeira** [nijicha/install_nodejs_and_yarn_homebrew#8]
I followed the steps, but when I run `nvm use` the node version doesn't change. My solution was to reinstall nodejs. Run `asdf uninstall nodejs` and `asdf install nodejs` (after completed steps). That way, nvm works normally.

**Comment by nijicha** [comment]
Greetings @joaoromeira,

From my understanding, You are trying to change NodeJS version manager from
`nvm` to `asdf` right?

> but when I run nvm to use the node version doesn't change

I think from the moment your terminal has two version managers `nvm` and `asdf`

If you wanna do like `nvm use` command. You can tell `asdf` to which installed nodejs will be used. with `asdf local` or `asdf global`

# Examples

Here is my `asdf list`
```shell
❯ asdf list
nodejs
  16.19.0
  *18.12.1
yarn
 *1.22.19
```

I have a legacy project which develops by `nodejs 16.19.0` version
But I wanna use the latest LTS version for every newly project.

So what do I do?

1. Set asdf to use nodejs 16.x locally for a legacy project
```shell
cd legacy_project
asdf local nodejs 16.19.0
```

2. Set asdf global to use `nodejs 18.12.1`

If I'm wrong please provide more information below. Don't hesitate to left your problem here. Cheer! 🍺
